language: android

android:
  components:
    - build-tools-21.0.2
    - android-21
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

before_install: export TERM=dumb

script: ./gradlew assembleDebug lintDebug testDebug

branches:
  only:
    - master
    - production